In [2]:
# Importing Library
import pandas as pd
from datasets import load_dataset
import matplotlib.pyplot as plt

# Loading Data
dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()

# Data Cleanup
df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

/opt/anaconda3/envs/python_course/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

In [4]:
median_salary_year = df['salary_year_avg'].median()

In [5]:
median_salary_hour = df['salary_hour_avg'].median()

In [ ]:
df_filled = df

df_filled['salary_year_avg'] = df_filled['salary_year_avg'].fillna(median_salary_year)
df_filled['salary_hour_avg'] = df_filled['salary_hour_avg'].fillna(median_salary_hour)

In [9]:
df_filled.loc[:10,'salary_year_avg':'salary_hour_avg']

    salary_year_avg  salary_hour_avg
0          115000.0            45.98
1          115000.0            45.98
2          115000.0            45.98
3          115000.0            45.98
4          115000.0            45.98
5          115000.0            45.98
6          115000.0            45.98
7          115000.0            45.98
8          115000.0            45.98
9          115000.0            45.98
10         115000.0            45.98

In [10]:
df_unique = df_filled

df_unique = df_unique.drop_duplicates()

print('Length of original df :      ',len(df_filled))
print('Length of drop duplicates df :   ',len(df_unique))
print('Rows Dropped :    ',len(df_filled)-len(df_unique))

Length of original df :       785741
Length of drop duplicates df :    785640
Rows Dropped :     101

In [11]:
df

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,United States,NaN,115000.0,45.98,Boehringer Ingelheim,NaN,NaN
1,Data Analyst,Data Analyst,"Guadalajara, Jalisco, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-14 13:18:07,False,False,Mexico,NaN,115000.0,45.98,Hewlett Packard Enterprise,"['r', 'python', 'sql', 'nosql', 'power bi', 't...","{'analyst_tools': ['power bi', 'tableau'], 'pr..."
2,Data Engineer,"Data Engineer/Scientist/Analyst, Mid or Senior...","Berlin, Germany",via LinkedIn,Full-time,False,Germany,2023-10-10 13:14:55,False,False,Germany,NaN,115000.0,45.98,ALPHA Augmented Services,"['python', 'sql', 'c#', 'azure', 'airflow', 'd...","{'analyst_tools': ['dax'], 'cloud': ['azure'],..."
3,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com,Full-time,False,"Texas, United States",2023-07-04 13:01:41,True,False,United States,NaN,115000.0,45.98,Southwest Research Institute,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',..."
4,Data Engineer,Data Engineer- Sr Jobs,"Washington, DC",via Clearance Jobs,Full-time,False,Sudan,2023-08-07 14:29:36,False,False,Sudan,NaN,115000.0,45.98,Kristina Daniel,"['bash', 'python', 'oracle', 'aws', 'ansible',...","{'cloud': ['oracle', 'aws'], 'other': ['ansibl..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
785736,Software Engineer,DevOps Engineer,Singapura,melalui Trabajo.org,Pekerjaan tetap,False,Singapore,2023-03-13 06:16:16,False,False,Singapore,NaN,115000.0,45.98,CAREERSTAR INTERNATIONAL PTE. LTD.,"['bash', 'python', 'perl', 'linux', 'unix', 'k...","{'os': ['linux', 'unix'], 'other': ['kubernete..."
785737,Data Analyst,CRM Data Analyst,"Bad Rodach, Jerman",melalui BeBee Deutschland,Pekerjaan tetap,False,Germany,2023-03-12 06:18:18,False,False,Germany,NaN,115000.0,45.98,HABA FAMILYGROUP,"['sas', 'sas', 'sql', 'excel']","{'analyst_tools': ['sas', 'excel'], 'programmi..."
785738,Business Analyst,Commercial Analyst - Start Now,Malaysia,melalui Ricebowl,Pekerjaan tetap,False,Malaysia,2023-03-12 06:32:36,False,False,Malaysia,NaN,115000.0,45.98,Lendlease Corporation,"['powerpoint', 'excel']","{'analyst_tools': ['powerpoint', 'excel']}"
785739,Data Engineer,"Principal Associate, Data Engineer (Remote-Eli...","Newark, New Jersey, Amerika Serikat",melalui Recruit.net,Pekerjaan tetap,False,Sudan,2023-03-12 06:32:15,False,False,Sudan,NaN,115000.0,45.98,Capital One,"['python', 'go', 'nosql', 'sql', 'mongo', 'she...","{'cloud': ['aws', 'snowflake', 'azure', 'redsh..."
785740,Software Engineer,AWS System Analyst,India,melalui Trigyn,Pekerjaan tetap,False,India,2023-03-13 06:16:31,False,False,India,NaN,115000.0,45.98,Trigyn,"['aws', 'flow']","{'cloud': ['aws'], 'other': ['flow']}"

In [12]:
df_unique = df_unique.drop_duplicates(subset=['job_title', 'company_name'])

print('Length of original df :      ',len(df_filled))
print('Length of drop duplicates df :   ',len(df_unique))
print('Rows Dropped :    ',len(df_filled)-len(df_unique))

Length of original df :       785741
Length of drop duplicates df :    508042
Rows Dropped :     277699

In [3]:
df.sample(10)

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
501208,Software Engineer,Product Analyst,"Birmingham, UK",via LinkedIn,Full-time,False,United Kingdom,2023-11-07 11:35:21,True,False,United Kingdom,NaN,NaN,NaN,AND Digital Nederland,NaN,NaN
667569,Data Analyst,Medical Data Analyst,"Columbia, SC",via Trabajo.org,Full-time,False,Georgia,2023-11-25 11:08:39,False,True,United States,NaN,NaN,NaN,BlueCross BlueShield of South Carolina,"['sql', 'visual basic', 'go', 'db2', 'excel', ...","{'analyst_tools': ['excel', 'power bi', 'table..."
152417,Machine Learning Engineer,Senior Machine Learning/ AI Engineer (f/m/d) B...,"Berlin, Germany",via SmartRecruiters Job Search,Full-time,False,Germany,2023-07-25 08:22:42,False,False,Germany,NaN,NaN,NaN,SIGNA Sports United,"['sql', 'aws']","{'cloud': ['aws'], 'programming': ['sql']}"
271179,Business Analyst,Mongo DB Data Business Analyst,"Brussels, Belgium",via Skillfinder International,Full-time,False,Belgium,2023-12-13 08:19:47,True,False,Belgium,NaN,NaN,NaN,Skillfinder,"['mongo', 'mongodb', 'mongodb', 'python', 'she...","{'cloud': ['azure', 'oracle'], 'databases': ['..."
534391,Data Scientist,Research Analyst,Singapore,via LinkedIn,Full-time,False,Singapore,2023-06-02 19:42:27,False,False,Singapore,NaN,NaN,NaN,RTG BUSINESS CONSULTING SERVICES PTE. LTD.,NaN,NaN
706329,Data Analyst,Data Analyst,Dubai - United Arab Emirates,via BeBee,Full-time,False,United Arab Emirates,2023-12-30 02:14:33,True,False,United Arab Emirates,NaN,NaN,NaN,Emarat Careers,NaN,NaN
600736,Data Engineer,Data Engineer,"Hsinchu, Hsinchu City, Taiwan",via LinkedIn,NaN,False,Taiwan,2023-08-19 09:17:11,False,False,Taiwan,NaN,NaN,NaN,英特爾,"['python', 'sql', 'r', 'azure', 'power bi', 'd...","{'analyst_tools': ['power bi', 'dax', 'excel']..."
23180,Data Engineer,Data Engineer/Senior Data Engineer,"London, UK",via WJHL Jobs,Full-time,False,United Kingdom,2023-07-14 13:16:31,True,False,United Kingdom,NaN,NaN,NaN,Henderson Scott,['azure'],{'cloud': ['azure']}
8398,Data Analyst,Data Analyst,"Columbia, SC",via Jobs Trabajo.org,Full-time,False,Georgia,2023-08-06 14:30:54,False,False,United States,NaN,NaN,NaN,SynergisticIT,"['python', 'scala', 'django']","{'programming': ['python', 'scala'], 'webframe..."
432878,Senior Data Analyst,Manager Data Analytics,Dubai - United Arab Emirates,via Jooble,Full-time,False,United Arab Emirates,2023-09-04 16:19:59,False,False,United Arab Emirates,NaN,NaN,NaN,Global Hotel Alliance,"['sql', 'python', 'power bi']","{'analyst_tools': ['power bi'], 'programming':..."